<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Нам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработаем такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось.

## Загрузка данных

In [1]:
# Загрузим все необходимые библиотеки:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import warnings 
warnings.filterwarnings('ignore')

In [2]:
# Выведем данные:
data = pd.read_csv('/datasets/insurance.csv')
data.info()
display(data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

* Признаки: пол, возраст и зарплата застрахованного, количество членов его семьи.
* Целевой признак - количество страховых выплат клиенту.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

Ответьте на вопрос и обоснуйте решение.
Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)
* a. Изменится. Приведите примеры матриц.
* b. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.

**Ответ:** Качество линейной регрессии не изменится.

**Обоснование:** 
Для преобразования данных предлагается умножить матрицу признаков X на рандомную матрицу P.

$$
X' = XP
$$

Рандомная матрица должна быть обратимой, т.е. быть квадратной - число строк и столбцов должно быть равно числу столбцов матрицы признаков.

Формула обучения:
$$
w = (X^T X)^{-1} X^T y
$$

Формула предсказания:
$$
a = Xw = X (X^T X)^{-1} X^T y
$$

Следует выделить свойства матриц:
$$AA^{-1} = E$$
$$(AB)^T = B^TA^T$$
$$(AB)^{-1} = B^{-1}A^{-1}$$
$$(AB)C = A(BC)$$
$$(ABCD)^{-1} = ((ABC)D)^{-1} = (A(BCD))^{-1}$$

В результате должно получиться:
$$ a' = a.$$

Подставим новую матрицу X' в формулу предсказания a' (y можно опустить):

$$
a' = XP((XP)^T XP)^{-1} (XP)^T = X P(P^T (X^T X) P)^{-1} P^T X^T =
$$

$$
X P P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T = X E (X^T X)^{-1} E X^T
$$

Получается в результате вычислений рандомная обратимая матрица трансформируется в единичную матрицу и на результат не влияет, т.к.:

$$
AE = A
$$

## Алгоритм преобразования

Предложите алгоритм преобразования данных для решения задачи. Обоснуйте, почему качество линейной регрессии не поменяется.

**Алгоритм**

Предлагается умножить признаки на рандомную обратимую (квадратную) матрицу.

In [3]:
# Проверим изменится ли качество линейно регрессии при умножении признаков на обратимую матрицу:
X = np.array([[1, 2, 5, 4],
              [1, 6, 7, 8],
              [1, 2, 8, 10],
              [1, 22, 8, 10],
              [1, 2, 38, 10]])

y = np.array([5, 2, 1, 4, 1])

P = np.random.randint(1,100, size=(4,4))
X1 = X.dot(P)

# Формула обучения:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w1 = np.linalg.inv(X1.T @ X1) @ X1.T @ y

# Предсказания:
a = X @ w
print(a)
a1 = X1 @ w1
print(a1)

[4.77272727 2.68181818 0.68181818 3.86363636 1.        ]
[4.77272727 2.68181818 0.68181818 3.86363636 1.        ]


**Обоснование**

При умножении матрицы на рандомную обратимую матрицу результат предсказания не меняется в соотвествии с доказательством в разделе 2, т.е. качество линейной регрессии не поменяется.

## Проверка алгоритма

In [4]:
# Выделим признаки:
features = data.drop('Страховые выплаты', axis=1)
target = data['Страховые выплаты']
print("Признаки до изменения:")
print(features.head())

Признаки до изменения:
   Пол  Возраст  Зарплата  Члены семьи
0    1     41.0   49600.0            1
1    0     46.0   38000.0            1
2    0     29.0   21000.0            0
3    0     21.0   41700.0            2
4    1     28.0   26100.0            0


In [5]:
# Создадим рандомную матрицу:
random_matrix = np.random.randint(1,100, size=(4,4))

while np.linalg.det(random_matrix) == 0:
    random_matrix = np.random.randint(1,100, size=(4,4))

print('Рандомная матрица:\n', random_matrix)
print("Детерминант матрицы:\n", np.linalg.det(random_matrix))

Рандомная матрица:
 [[75 98 25 25]
 [64 53 79 96]
 [86 50 65 12]
 [38 27 39  6]]
Детерминант матрицы:
 -5206036.000000004


In [6]:
# Умножим признаки на рандомную матрицу для сокрытия персональных данных:
features_new = features @ random_matrix
print("Признаки после изменения:") 
print(features_new.head())

Признаки после изменения:
           0          1          2         3
0  4268337.0  2482298.0  3227303.0  599167.0
1  3270982.0  1902465.0  2473673.0  460422.0
2  1807856.0  1051537.0  1367291.0  254784.0
3  3587620.0  2086167.0  2712237.0  502428.0
4  2246467.0  1306582.0  1698737.0  315913.0


In [7]:
# Рассчитаем R2 на признаках до их изменения:
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

0.4249455028666801


In [8]:
# Рассчитаем R2 на признаках после их изменения:
model_new = LinearRegression()
model_new.fit(features_new, target)
predictions_new = model_new.predict(features_new)
print(r2_score(target, predictions_new))

0.4249455028666711


**Вывод:** Значения R2 в обоих случаях совпадают. Можно с уверенностью использовать предложенный метод.